[Icon Theme]
Name=Reversal Extra
Inherits=Reversal,Numix-Circle-Light,Adwaita,hicolor

Directories=apps/scalable,status/16,status/22,status/24,status/32,status/symbolic,status@2x/16,status@2x/22,status@2x/24,status@2x/32,status@2x/symbolic,status@3x/16,status@3x/22,status@3x/24,status@3x/32,status@3x/symbolic

[apps/scalable]
Size=64
Scale=2
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[status/16]
Size=16
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status/symbolic]
Size=16
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

# @2x

[status@2x/16]
Size=16
Scale=2
Context=Status
Type=Fixed

[status@2x/22]
Size=22
Scale=2
Context=Status
Type=Fixed

[status@2x/24]
Size=24
Scale=2
Context=Status
Type=Fixed

[status@2x/32]
Size=32
Scale=2
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status@2x/symbolic]
Size=16
Scale=2
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

# @3x

[status@3x/16]
Size=16
Scale=3
Context=Status
Type=Fixed

[status@3x/22]
Size=22
Scale=3
Context=Status
Type=Fixed

[status@3x/24]
Size=24
Scale=3
Context=Status
Type=Fixed

[status@3x/32]
Size=32
Scale=3
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status@3x/symbolic]
Size=16
Scale=3
Context=Status
MinSize=16
MaxSize=512
Type=Scalable
